### PR TITLE
Fixing banshee link

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @Enapiuz 

just fixing the broken link for Banshee.

Cheers!

### CODE REVIEW

**Comment by Enapiuz** [comment]
Thanks 😄

**Comment by spekulatius** [comment]
No worries, happy to help out!

**Comment by spekulatius** [comment]
Btw @Enapiuz, the list could be found easier if you add some topics. Just thought I let you know...

**Comment by Enapiuz** [comment]
Seems like I completely forgot about them lol.
Will take a closer look, thank you so much 😄

**Comment by spekulatius** [comment]
Cool :+1:

**Pull request merged**
